name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Release'

jobs:
  testflight:
    name: TestFlight
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: |
          brew tap wix/brew
          brew install applesimutils
      - uses: actions/checkout@v2
      - run: yarn
      - run: |
          cd packages/mobile
          bundle install
      - run: yarn build:wallet
